"""
@kerliix/icons-python — build script
Reads every SVG from packages/icons/icons/ and generates:
  kerliix_icons/__init__.py  — typed Python module with one constant per icon
  kerliix_icons/py.typed     — PEP 561 marker (ships type info)
"""
import os
import re

HERE      = os.path.dirname(os.path.abspath(__file__))
ICONS_DIR = os.path.join(HERE, '..', 'icons', 'icons')
OUT_DIR   = os.path.join(HERE, 'kerliix_icons')

os.makedirs(OUT_DIR, exist_ok=True)

svg_files = sorted(f for f in os.listdir(ICONS_DIR) if f.endswith('.svg'))
names     = [os.path.splitext(f)[0] for f in svg_files]   # filename = export name

lines = [
    '# kerliix_icons/__init__.py — generated by build.py, do not edit',
    '"""Kerliix Icons — SVG strings for every icon in the Kerliix library."""',
    '',
    'from __future__ import annotations',
    '',
    '__all__ = [',
    *[f'    "{n}",' for n in names],
    '    "get_icon",',
    '    "list_icons",',
    ']',
    '',
]

for file, name in zip(svg_files, names):
    raw = open(os.path.join(ICONS_DIR, file), encoding='utf-8').read()
    # Escape any backslashes, then triple-quote delimiters
    escaped = raw.replace('\\', '\\\\').replace('"""', '\\"\\"\\"')
    lines.append(f'#: SVG string for ``{name}``')
    lines.append(f'{name}: str = """{escaped}"""')
    lines.append('')
    print(f'  ✓ {name}')

lines += [
    '_ICONS: dict[str, str] = {',
    *[f'    "{n}": {n},' for n in names],
    '}',
    '',
    '',
    'def get_icon(name: str) -> str | None:',
    '    """Return the SVG string for *name*, or ``None`` if not found.',
    '',
    '    Example:',
    '        >>> svg = get_icon("KerliixIcon")',
    '    """',
    '    return _ICONS.get(name)',
    '',
    '',
    'def list_icons() -> list[str]:',
    '    """Return a sorted list of all available icon names."""',
    '    return sorted(_ICONS)',
]

open(os.path.join(OUT_DIR, '__init__.py'), 'w', encoding='utf-8').write('\n'.join(lines) + '\n')

# PEP 561 — tells type checkers this package ships inline types
open(os.path.join(OUT_DIR, 'py.typed'), 'w').close()

print(f'\nkerliix-icons (Python): built {len(names)} icons → kerliix_icons/')
